export const adminFormFields = {
  common: {
    tab: "tab",
    id: "id",
  },
  product: {
    name: "name",
    slug: "slug",
    subtitle: "subtitle",
    description: "description",
    additionalInfo: "additional_info",
    fulfillmentNote: "fulfillment_note",
    personalizationInfo: "personalization_info",
    dimensionsMaterials: "dimensions_materials",
    orderingInfo: "ordering_info",
    price: "price",
    imageFile: "image_file",
    imageFiles: "image_files",
    imageAltTexts: "image_alt_text[]",
    existingImageUrl: "existing_image_url",
    isCustomizable: "is_customizable",
    isSoldOut: "is_sold_out",
    fulfillmentType: "fulfillment_type",
    stockQuantity: "stock_quantity",
    cardBadge: "card_badge",
    categoryIds: "category_ids",
    primaryCategoryId: "primary_category_id",
    wishTemplateIds: "wish_template_ids",
    faqGroupIds: "product_faq_group_ids",
    faqItemIds: "product_faq_item_ids",
    metaTitle: "meta_title",
    metaDescription: "meta_description",
    ogTitle: "og_title",
    ogDescription: "og_description",
    status: "status",
  },
  category: {
    name: "name",
    slug: "slug",
    type: "category_type",
    parentId: "parent_id",
    imageFile: "category_image_file",
    imageAlt: "category_image_alt",
    coverImageFile: "category_cover_image_file",
    coverImageAlt: "category_cover_image_alt",
    cardDescription: "card_description",
    heroDescription: "hero_description",
    listingHeading: "listing_heading",
    introText: "intro_text",
    seoBody: "seo_body",
    metaTitle: "meta_title",
    metaDescription: "meta_description",
    ogTitle: "og_title",
    ogDescription: "og_description",
    robotsIndex: "robots_index",
    showOnHome: "show_on_home",
    isVisible: "is_visible",
    direction: "direction",
    relatedCategoryIds: "related_category_ids",
  },
  productImage: {
    imageId: "image_id",
    altText: "image_alt_text",
    direction: "direction",
    replaceFile: "replace_image_file",
  },
  merchandising: {
    isFeatured: "is_featured",
    homeSortOrder: "home_sort_order",
    relatedProductIds: "related_product_ids",
  },
  colorPalette: {
    groupId: "group_id",
    label: "label",
    optionId: "option_id",
    name: "name",
    hex: "hex",
    direction: "direction",
  },
  colorField: {
    labels: "color_field_label[]",
    groupIds: "color_field_group_id[]",
    minSelects: "color_field_min_select[]",
    maxSelects: "color_field_max_select[]",
    optionIds: "color_field_option_ids[]",
    selectionModes: "color_field_selection_mode[]",
    requiredTotalQuantities: "color_field_required_total_quantity[]",
  },
  personalizationField: {
    labels: "personalization_label[]",
    keys: "personalization_key[]",
    types: "personalization_type[]",
    placeholders: "personalization_placeholder[]",
    maxLengths: "personalization_max_length[]",
    priceDeltas: "personalization_price_delta[]",
    required: "personalization_required[]",
    allowsWishes: "personalization_allows_wishes[]",
  },
  optionGroup: {
    ids: "option_group_id[]",
    names: "option_group_name[]",
    keys: "option_group_key[]",
    inputTypes: "option_group_input_type[]",
    required: "option_group_required[]",
    minSelects: "option_group_min_select[]",
    maxSelects: "option_group_max_select[]",
    sortOrders: "option_group_sort_order[]",
    active: "option_group_active[]",
    dependsOnOptionIds: "option_group_depends_on[]",
    placeholders: "option_group_placeholder[]",
    maxLengths: "option_group_max_length[]",
    textPriceDeltas: "option_group_text_price_delta[]",
    valuesJson: "option_group_values_json[]",
  },
  eventGallery: {
    imageFiles: "event_gallery_files",
    defaultAlt: "event_gallery_default_alt",
    imageId: "event_gallery_image_id",
    direction: "direction",
  },
  promotion: {
    id: "promotion_id",
    productId: "product_id",
    name: "name",
    discountType: "discount_type",
    discountValue: "discount_value",
    startsAt: "starts_at",
    endsAt: "ends_at",
    isActive: "is_active",
    productIds: "product_ids",
    campaignId: "campaign_id",
  },
  landingPage: {
    id: "landing_page_id",
    productId: "product_id",
    productSlug: "product_slug",
    title: "landing_title",
    slug: "landing_slug",
    campaignCode: "landing_campaign_code",
    isPrimary: "landing_is_primary",
    isActive: "landing_is_active",
    sortOrder: "landing_sort_order",
  },
  siteMedia: {
    key: "site_media_key",
    imageFile: "site_media_image_file",
    imageAlt: "site_media_image_alt",
  },
  faq: {
    groupId: "faq_group_id",
    groupName: "faq_group_name",
    groupSlug: "faq_group_slug",
    groupScope: "faq_group_scope",
    groupSortOrder: "faq_group_sort_order",
    groupIsActive: "faq_group_is_active",
    itemId: "faq_item_id",
    itemQuestion: "faq_item_question",
    itemAnswer: "faq_item_answer",
    itemSortOrder: "faq_item_sort_order",
    itemIsActive: "faq_item_is_active",
    groupItemIds: "faq_group_item_ids",
    direction: "faq_direction",
  },
} as const;
