export const adminFormFields = {
  common: {
    tab: "tab",
    id: "id",
  },
  product: {
    name: "name",
    description: "description",
    additionalInfo: "additional_info",
    fulfillmentNote: "fulfillment_note",
    price: "price",
    imageFile: "image_file",
    imageFiles: "image_files",
    existingImageUrl: "existing_image_url",
    isCustomizable: "is_customizable",
    isSoldOut: "is_sold_out",
    cardBadge: "card_badge",
    categoryIds: "category_ids",
    wishTemplateIds: "wish_template_ids",
  },
  category: {
    name: "name",
    slug: "slug",
    type: "category_type",
    showOnHome: "show_on_home",
    direction: "direction",
  },
  productImage: {
    imageId: "image_id",
    direction: "direction",
  },
  colorPalette: {
    groupId: "group_id",
    label: "label",
    optionId: "option_id",
    name: "name",
    hex: "hex",
    direction: "direction",
  },
  colorField: {
    labels: "color_field_label[]",
    groupIds: "color_field_group_id[]",
    minSelects: "color_field_min_select[]",
    maxSelects: "color_field_max_select[]",
    optionIds: "color_field_option_ids[]",
  },
  personalizationField: {
    labels: "personalization_label[]",
    keys: "personalization_key[]",
    types: "personalization_type[]",
    placeholders: "personalization_placeholder[]",
    maxLengths: "personalization_max_length[]",
    required: "personalization_required[]",
    allowsWishes: "personalization_allows_wishes[]",
  },
  eventGallery: {
    imageFiles: "event_gallery_files",
    defaultAlt: "event_gallery_default_alt",
    imageId: "event_gallery_image_id",
    direction: "direction",
  },
  promotion: {
    id: "promotion_id",
    productId: "product_id",
    name: "name",
    discountType: "discount_type",
    discountValue: "discount_value",
    startsAt: "starts_at",
    endsAt: "ends_at",
    isActive: "is_active",
  },
} as const;
