export const adminFormFields = {
  common: {
    tab: "tab",
    id: "id",
  },
  product: {
    name: "name",
    description: "description",
    additionalInfo: "additional_info",
    fulfillmentNote: "fulfillment_note",
    price: "price",
    imageFile: "image_file",
    imageFiles: "image_files",
    existingImageUrl: "existing_image_url",
    isCustomizable: "is_customizable",
    isSoldOut: "is_sold_out",
    cardBadge: "card_badge",
    categoryIds: "category_ids",
    wishTemplateIds: "wish_template_ids",
  },
  category: {
    name: "name",
    slug: "slug",
    type: "category_type",
    cardDescription: "card_description",
    showOnHome: "show_on_home",
    direction: "direction",
  },
  productImage: {
    imageId: "image_id",
    direction: "direction",
    replaceFile: "replace_image_file",
  },
  merchandising: {
    isFeatured: "is_featured",
    homeSortOrder: "home_sort_order",
    relatedProductIds: "related_product_ids",
  },
  colorPalette: {
    groupId: "group_id",
    label: "label",
    optionId: "option_id",
    name: "name",
    hex: "hex",
    direction: "direction",
  },
  colorField: {
    labels: "color_field_label[]",
    groupIds: "color_field_group_id[]",
    minSelects: "color_field_min_select[]",
    maxSelects: "color_field_max_select[]",
    optionIds: "color_field_option_ids[]",
  },
  personalizationField: {
    labels: "personalization_label[]",
    keys: "personalization_key[]",
    types: "personalization_type[]",
    placeholders: "personalization_placeholder[]",
    maxLengths: "personalization_max_length[]",
    priceDeltas: "personalization_price_delta[]",
    required: "personalization_required[]",
    allowsWishes: "personalization_allows_wishes[]",
  },
  optionGroup: {
    ids: "option_group_id[]",
    names: "option_group_name[]",
    keys: "option_group_key[]",
    inputTypes: "option_group_input_type[]",
    required: "option_group_required[]",
    minSelects: "option_group_min_select[]",
    maxSelects: "option_group_max_select[]",
    sortOrders: "option_group_sort_order[]",
    active: "option_group_active[]",
    dependsOnOptionIds: "option_group_depends_on[]",
    placeholders: "option_group_placeholder[]",
    maxLengths: "option_group_max_length[]",
    textPriceDeltas: "option_group_text_price_delta[]",
    valuesJson: "option_group_values_json[]",
  },
  eventGallery: {
    imageFiles: "event_gallery_files",
    defaultAlt: "event_gallery_default_alt",
    imageId: "event_gallery_image_id",
    direction: "direction",
  },
  promotion: {
    id: "promotion_id",
    productId: "product_id",
    name: "name",
    discountType: "discount_type",
    discountValue: "discount_value",
    startsAt: "starts_at",
    endsAt: "ends_at",
    isActive: "is_active",
    productIds: "product_ids",
    campaignId: "campaign_id",
  },
} as const;
